// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArl5Dubc47z4XqWhaH9uJ16Rrr7iLq-iw',
    appId: '1:784219103655:web:8f0bc89183db3a7a961682',
    messagingSenderId: '784219103655',
    projectId: 'investhelper-2024',
    authDomain: 'investhelper-2024.firebaseapp.com',
    storageBucket: 'investhelper-2024.appspot.com',
    measurementId: 'G-ZYTB0MQM9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZeddvTavt-peVT9VLfGm_HLamZJniVIE',
    appId: '1:784219103655:android:935ddb173e7416f1961682',
    messagingSenderId: '784219103655',
    projectId: 'investhelper-2024',
    storageBucket: 'investhelper-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzrnwuc5tdQ9ErQ7nIslWe56oRTgR1E8',
    appId: '1:784219103655:ios:14e04dda8a5b4e39961682',
    messagingSenderId: '784219103655',
    projectId: 'investhelper-2024',
    storageBucket: 'investhelper-2024.appspot.com',
    iosBundleId: 'com.eduardoazevedo.investhelper',
  );
}
